### ISSUE TITLE
Error in Log

### ISSUE THREAD

**Issue by vr6syncro** [nisiode/ioBroker.iogo#6]
Hi, ich habe folgende Errors im log stehen.

`

host.ioBroker | 2018-10-14 11:11:37.645 | info | Restart adapter system.adapter.iogo.0 because enabled
-- | -- | -- | --
host.ioBroker | 2018-10-14 11:11:37.645 | error | instance system.adapter.iogo.0 terminated with code 0 (OK)
host.ioBroker | 2018-10-14 11:11:37.644 | error | Caught by controller[1]: at /opt/iobroker/node_modules/iobroker.iogo/main.js:239:38
host.ioBroker | 2018-10-14 11:11:37.644 | error | Caught by controller[1]: at Reference.set (/opt/iobroker/node_modules/@firebase/database/dist/index.node.cjs.js:13963:9)
host.ioBroker | 2018-10-14 11:11:37.644 | error | Caught by controller[1]: at validateFirebaseDataArg (/opt/iobroker/node_modules/@firebase/database/dist/index.node.cjs.js:1421:5)
host.ioBroker | 2018-10-14 11:11:37.644 | error | Caught by controller[1]: at validateFirebaseData (/opt/iobroker/node_modules/@firebase/database/dist/index.node.cjs.js:1462:14)
host.ioBroker | 2018-10-14 11:11:37.644 | error | Caught by controller[1]: at Object.forEach (/opt/iobroker/node_modules/@firebase/util/dist/index.node.cjs.js:837:13)
host.ioBroker | 2018-10-14 11:11:37.644 | error | Caught by controller[1]: at /opt/iobroker/node_modules/@firebase/database/dist/index.node.cjs.js:1479:13
host.ioBroker | 2018-10-14 11:11:37.643 | error | Caught by controller[1]: at validateFirebaseData (/opt/iobroker/node_modules/@firebase/database/dist/index.node.cjs.js:1462:14)
host.ioBroker | 2018-10-14 11:11:37.643 | error | Caught by controller[1]: at Object.forEach (/opt/iobroker/node_modules/@firebase/util/dist/index.node.cjs.js:837:13)
host.ioBroker | 2018-10-14 11:11:37.643 | error | Caught by controller[1]: at /opt/iobroker/node_modules/@firebase/database/dist/index.node.cjs.js:1479:13
host.ioBroker | 2018-10-14 11:11:37.643 | error | Caught by controller[1]: at validateFirebaseData (/opt/iobroker/node_modules/@firebase/database/dist/index.node.cjs.js:1433:15)
host.ioBroker | 2018-10-14 11:11:37.643 | error | Caught by controller[1]: Error: Reference.set failed: First argument contains undefined in property 'enums.zBokDyHN49YrnG6Qzim5NPlR8gG3.enum_favorites.members'
host.ioBroker | 2018-10-14 11:11:37.642 | error | Caught by controller[0]: at process._tickCallback (internal/process/next_tick.js:109:7)
host.ioBroker | 2018-10-14 11:11:37.642 | error | Caught by controller[0]: at /opt/iobroker/node_modules/@firebase/util/dist/index.node.cjs.js:1453:21
host.ioBroker | 2018-10-14 11:11:37.642 | error | Caught by controller[0]: at /opt/iobroker/node_modules/@firebase/util/dist/index.node.cjs.js:1349:22
host.ioBroker | 2018-10-14 11:11:37.642 | error | Caught by controller[0]: at Object.next (/opt/iobroker/node_modules/iobroker.iogo/main.js:167:11)
host.ioBroker | 2018-10-14 11:11:37.642 | error | Caught by controller[0]: at removeListener (/opt/iobroker/node_modules/iobroker.iogo/main.js:361:21)
host.ioBroker | 2018-10-14 11:11:37.641 | error | Caught by controller[0]: TypeError: Cannot read property 'off' of undefined
iogo.0 | 2018-10-14 11:11:37.014 | info | signed out
iogo.0 | 2018-10-14 11:11:37.014 | info | cleaned everything up...
iogo.0 | 2018-10-14 11:11:37.014 | error | Error: Reference.set failed: First argument contains undefined in property 'enums.zBokDyHN49YrnG6Qzim5NPlR8gG3.enum_favorites.members' at validateFirebaseData (/opt/iobroker/node_modules/@firebase
iogo.0 | 2018-10-14 11:11:37.014 | error | uncaught exception: Reference.set failed: First argument contains undefined in property 'enums.zBokDyHN49YrnG6Qzim5NPlR8gG3.enum_favorites.members'

`

**Comment by nisiode** [comment]
hab den Fehler gefunden.
wird in der nächsten Version behoben
