### ISSUE TITLE
Errors 0.1.1

### ISSUE THREAD

**Issue by vr6syncro** [nisiode/ioBroker.iogo#8]
Hi habe immer noch error hatte gestern geupdatet aber adapter läuft leider immer noch nicht.

`

host.ioBroker | 2018-11-01 12:15:34.468 | info | object change system.adapter.iogo.0
-- | -- | -- | --
host.ioBroker | 2018-11-01 12:15:32.018 | info | Restart adapter system.adapter.iogo.0 because enabled
host.ioBroker | 2018-11-01 12:15:32.018 | error | instance system.adapter.iogo.0 terminated with code 0 (OK)
Caught | 2018-11-01 12:15:32.018 | error | by controller[0]: at /opt/iobroker/node_modules/iobroker.iogo/main.js:218:38
Caught | 2018-11-01 12:15:32.018 | error | by controller[0]: at Reference.set (/opt/iobroker/node_modules/iobroker.iogo/node_modules/@firebase/database/dist/index.node.cjs.js:13963:9)
Caught | 2018-11-01 12:15:32.018 | error | by controller[0]: at validateFirebaseDataArg (/opt/iobroker/node_modules/iobroker.iogo/node_modules/@firebase/database/dist/index.node.cjs.js:1421:5)
Caught | 2018-11-01 12:15:32.018 | error | by controller[0]: at validateFirebaseData (/opt/iobroker/node_modules/iobroker.iogo/node_modules/@firebase/database/dist/index.node.cjs.js:1462:14)
Caught | 2018-11-01 12:15:32.018 | error | by controller[0]: at Object.forEach (/opt/iobroker/node_modules/iobroker.iogo/node_modules/@firebase/util/dist/index.node.cjs.js:837:13)
Caught | 2018-11-01 12:15:32.018 | error | by controller[0]: at /opt/iobroker/node_modules/iobroker.iogo/node_modules/@firebase/database/dist/index.node.cjs.js:1479:13
Caught | 2018-11-01 12:15:32.018 | error | by controller[0]: at validateFirebaseData (/opt/iobroker/node_modules/iobroker.iogo/node_modules/@firebase/database/dist/index.node.cjs.js:1462:14)
Caught | 2018-11-01 12:15:32.018 | error | by controller[0]: at Object.forEach (/opt/iobroker/node_modules/iobroker.iogo/node_modules/@firebase/util/dist/index.node.cjs.js:837:13)
Caught | 2018-11-01 12:15:32.018 | error | by controller[0]: at /opt/iobroker/node_modules/iobroker.iogo/node_modules/@firebase/database/dist/index.node.cjs.js:1479:13
Caught | 2018-11-01 12:15:32.017 | error | by controller[0]: at validateFirebaseData (/opt/iobroker/node_modules/iobroker.iogo/node_modules/@firebase/database/dist/index.node.cjs.js:1433:15)
Caught | 2018-11-01 12:15:32.017 | error | by controller[0]: Error: Reference.set failed: First argument contains undefined in property 'enums.zBokDyHN49YrnG6Qzim5NPlR8gG3.enum_favorites.members'
iogo.0 | 2018-11-01 12:15:31.987 | info | terminating
iogo.0 | 2018-11-01 12:15:31.531 | info | signed out
iogo.0 | 2018-11-01 12:15:31.527 | info | cleaned everything up...
iogo.0 | 2018-11-01 12:15:31.527 | error | at /opt/iobroker/node_modules/iobroker.iogo/main.js:218:38
iogo.0 | 2018-11-01 12:15:31.527 | error | at Reference.set (/opt/iobroker/node_modules/iobroker.iogo/node_modules/@firebase/database/dist/index.node.cjs.js:13963:9)
iogo.0 | 2018-11-01 12:15:31.527 | error | at validateFirebaseDataArg (/opt/iobroker/node_modules/iobroker.iogo/node_modules/@firebase/database/dist/index.node.cjs.js:1421:5)
iogo.0 | 2018-11-01 12:15:31.527 | error | at validateFirebaseData (/opt/iobroker/node_modules/iobroker.iogo/node_modules/@firebase/database/dist/index.node.cjs.js:1462:14)
iogo.0 | 2018-11-01 12:15:31.527 | error | at Object.forEach (/opt/iobroker/node_modules/iobroker.iogo/node_modules/@firebase/util/dist/index.node.cjs.js:837:13)
iogo.0 | 2018-11-01 12:15:31.527 | error | at /opt/iobroker/node_modules/iobroker.iogo/node_modules/@firebase/database/dist/index.node.cjs.js:1479:13
iogo.0 | 2018-11-01 12:15:31.527 | error | at validateFirebaseData (/opt/iobroker/node_modules/iobroker.iogo/node_modules/@firebase/database/dist/index.node.cjs.js:1462:14)
iogo.0 | 2018-11-01 12:15:31.527 | error | at Object.forEach (/opt/iobroker/node_modules/iobroker.iogo/node_modules/@firebase/util/dist/index.node.cjs.js:837:13)
iogo.0 | 2018-11-01 12:15:31.527 | error | at /opt/iobroker/node_modules/iobroker.iogo/node_modules/@firebase/database/dist/index.node.cjs.js:1479:13
iogo.0 | 2018-11-01 12:15:31.527 | error | at validateFirebaseData (/opt/iobroker/node_modules/iobroker.iogo/node_modules/@firebase/database/dist/index.node.cjs.js:1433:15)
iogo.0 | 2018-11-01 12:15:31.527 | error | Error: Reference.set failed: First argument contains undefined in property 'enums.zBokDyHN49YrnG6Qzim5NPlR8gG3.enum_favorites.members'
iogo.0 | 2018-11-01 12:15:31.526 | error | uncaught exception: Reference.set failed: First argument contains undefined in property 'enums.zBokDyHN49YrnG6Qzim5NPlR8gG3.enum_favorites.members'
iogo.0 | 2018-11-01 12:15:30.217 | info | removed enums from remote database
iogo.0 | 2018-11-01 12:15:30.215 | info | removed objects from remote database
iogo.0 | 2018-11-01 12:15:30.213 | info | removed states from remote database
iogo.0 | 2018-11-01 12:15:30.201 | info | logged in as: zBokDyHN49YrnG6Qzim5NPlR8gG3
iogo.0 | 2018-11-01 12:15:29.513 | info | initialize app devices
iogo.0 | 2018-11-01 12:15:29.447 | info | starting. Version 0.1.1 in /opt/iobroker/node_modules/iobroker.iogo, node: v6.14.4

`

**Comment by nisiode** [comment]
Kannst du Mal einen Screenshot oder den RAW von deinen enum.favorites Posten.

Hast du dort Einträge ohne zugeordnete member?

**Comment by vr6syncro** [comment]
Hoffe du meinste das hier: 
`
{
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1540831315524,
  "common": {
    "name": "Favorites"
  },
  "native": {},
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "_id": "enum.favorites",
  "type": "enum"
}
`

**Comment by nisiode** [comment]
hast du die Fehler auch mit version 0.1.2 noch?

**Comment by vr6syncro** [comment]
ja kommt auch noch

**Comment by ldittmar81** [comment]
Ich habe noch Version 0.1.1 drauf und bekomme auch den Fehler:

starting. Version 0.1.1 in /opt/iobroker/node_modules/iobroker.iogo, node: v6.11.3
initialize app devices
logged in as: ****************
removed states from remote database
removed objects from remote database
removed enums from remote database
uncaught exception: Reference.set failed: First argument contains undefined in property 'enums.****************.enum_favorites.members'
Error: Reference.set failed: First argument contains undefined in property 'enums.****************.enum_favorites.members'
...
at /opt/iobroker/node_modules/iobroker.iogo/main.js:218:38
cleaned everything up...
signed out
uncaught exception: Cannot set property 'id' of null
TypeError: Cannot set property 'id' of null

Unter enum.favorites habe ich nur ein Eintrag "Admin" und diese hat keine Members. Vielleicht liegt es daran?

**Comment by nisiode** [comment]
bitte erneut testen. 
es waren noch Fehler drin, mit dem raw aus https://github.com/nisiode/ioBroker.iogo/issues/8#issuecomment-435596790 funktioniert es bei mir
